In [1]:
import numpy as np

## Datatypes and attributes

##### ndarray

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1,2,3],[4,5,6]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[10,11,12],[13,14,15],[16,17,18]]])

In [5]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

##### attributes

In [6]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [7]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [8]:
a1.size, a2.size, a3.size

(3, 6, 18)

## Creating arrays

In [9]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [11]:
ones = np.ones((2, 3), dtype = int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
zrs = np.zeros((5,6))
zrs

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.random.randint(0, 10, size = (3, 5))

array([[0, 2, 8, 1, 7],
       [8, 4, 7, 1, 3],
       [1, 9, 1, 4, 9]])

In [16]:
np.random.random((5,3))

array([[0.39053631, 0.59335161, 0.72828087],
       [0.98022215, 0.5564343 , 0.20344353],
       [0.89480214, 0.74098635, 0.94349965],
       [0.34109736, 0.65961799, 0.36103065],
       [0.00868033, 0.09523753, 0.42583729]])

##### pseudo random

In [17]:
np.random.seed(7)
np.random.randint(100, 199, (2,20))

array([[147, 168, 125, 167, 183, 123, 192, 157, 114, 123, 172, 189, 142,
        190, 108, 139, 168, 148, 107, 144],
       [100, 175, 155, 106, 119, 160, 144, 163, 169, 156, 124, 155, 153,
        161, 164, 134, 156, 173, 178, 138]])

In [20]:
np.random.seed(7)
np.random.randint(100, 199, (2,15))

array([[147, 168, 125, 167, 183, 123, 192, 157, 114, 123, 172, 189, 142,
        190, 108],
       [139, 168, 148, 107, 144, 100, 175, 155, 106, 119, 160, 144, 163,
        169, 156]])

##### Viewing arrays and matrices

In [34]:
random_4d_array = np.random.randint(-50, 50, (2,3,4,5))

In [35]:
random_4d_array.shape, random_5d_array.size

((2, 3, 4, 5), 120)

In [36]:
random_4d_array

array([[[[ 37, -16, -30,   5,   2],
         [ 17, -37,  40, -18, -35],
         [ 15, -18, -49,  36,  11],
         [-49,  35, -36, -42,  42]],

        [[-31, -47,  23,  40, -27],
         [ -7,  15,  -3, -27,   5],
         [ 41,   9,  32, -23, -40],
         [-19,   6,  34, -47,   2]],

        [[-11,  40,   4,  46,   3],
         [ 27, -43, -24,   9,  -4],
         [ 11,  38,  41,  -2, -33],
         [-21, -21, -29,  25,  48]]],


       [[[  5,  -3,  20,  19,  23],
         [-40,  27,   4,  15, -15],
         [-45, -46, -39,  12,   0],
         [ -2, -32, -41, -46, -23]],

        [[ 11,  -2, -25, -48,  -9],
         [-34,   9,  15,  -6,  48],
         [-20,  19,  -4, -12,  40],
         [ 25,  17,   8, -17,   8]],

        [[ 13,  38,   2, -36,   2],
         [ -1,  31, -18,  15, -14],
         [ 13,  -2, -26, -25, -30],
         [-29,  35, -36, -24,  27]]]])

In [42]:
random_4d_array[1,2,0,:]

array([ 13,  38,   2, -36,   2])

In [43]:
random_4d_array[:, :, 0, :3]

array([[[ 37, -16, -30],
        [-31, -47,  23],
        [-11,  40,   4]],

       [[  5,  -3,  20],
        [ 11,  -2, -25],
        [ 13,  38,   2]]])

## Manipulating arrays

##### Arithmatic

In [44]:
a1 - np.ones(a1.shape)

array([0., 1., 2.])